kafka:
  brokers:
    - pkc-r21pp.us-east1.gcp.confluent.cloud:9092
  tls:
    enabled: true
  sasl:
    enabled: true
    username: PRIVATE
    password: PRIVATE
  protobuf:
    enabled: true
    mappings:
      - topicName: app.data.proto.external.lending.cloc.update.r1
        valueProtoType: cloc.app.AppCloc
        keyProtoType: UUID
      - topicName: app.data.proto.internal.chown.aggregation.apps.r1
        valueProtoType: ownership.Ownership
        keyProtoType: UUID
    fileSystem:
      paths:
        - /proto
      enabled: true
    git:
      enabled: false
      repository:
        url: https://github.com/FigureTechnologies/stream-data.git
        branch: master
        baseDirectory: src/main/proto
      basicAuth:
        enabled: false
        username: token
logger:
  level: debug