version: '3.5'

services:
  kowl:
    image: quay.io/cloudhut/kowl:master
    environment:
      GITHUB_TOKEN: $GITHUB_TOKEN
    volumes:
      - ./config.yaml:/tmp/config.yaml
      - ./proto:/proto
    entrypoint: ./kowl --config.filepath /tmp/config.yaml
    ports: 
      - 8081:8080
